#!/usr/bin/env bash

if [ -f /usr/bin/yay ]; then
  sudo /usr/bin/yay -Syu
elif [ -f /usr/bin/pacman ]; then
  sudo /usr/bin/pacman -Syu
fi

if [ -f /usr/bin/apt ]; then
  sudo /usr/bin/apt update
  sudo /usr/bin/apt upgrade -y
fi

if [ -f /usr/bin/flatpak ]; then
  sudo /usr/bin/flatpak update --noninteractive --assumeyes
fi
