#!/usr/bin/env bash

[ -f /usr/bin/pacman ] && \
  sudo pacman -Syu

[ -f /usr/bin/flatpak ] && \
  sudo /usr/bin/flatpak update --noninteractive --assumeyes

[ -f /usr/bin/emacs ] && \
  /usr/bin/emacs --eval '(progn (package-upgrade-all) (kill-emacs))'
